site_name: Nettux Docs
theme:
  name: material
  palette:
    primary: black
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences